/* =============================================================
   COSMOS — script.js
   Structure:
     1. CONFIG          – tunables
     2. DATA            – placeholder astronomy data (swap for a
                           live API later — see "DATA SOURCES" note)
     3. STARFIELD        – canvas background animation
     4. RENDERERS        – build DOM from DATA
     5. DETAIL OVERLAY    – click-through info panels
     6. NAV / SCROLL       – header behaviour, reveal-on-scroll
     7. INIT
   ============================================================= */

/* -------------------------------------------------------------
   1. CONFIG
------------------------------------------------------------- */
const CONFIG = {
  starfield: {
    density: 0.00012,     // stars per pixel²
    maxStars: 420,
    twinkleSpeed: 0.02,
    driftSpeed: 0.015,
  },
  orrery: {
    baseRadiusPct: 12,    // % of orrery width for innermost orbit
    radiusStepPct: 11,    // % spacing between orbits
  },
};

/* -------------------------------------------------------------
   2. DATA
   Placeholder, realistic reference figures for v1.
   ---------------------------------------------------------------
   DATA SOURCES (future): swap the arrays below for calls to
   NASA/JPL Horizons, NASA Open APIs, or the IAU minor planet
   center. Keep the same shape (id, name, key stats, blurb) so
   the renderers and the 3D layer don't need to change — only
   the fetch layer does. See fetchLiveData() stub at the bottom.
------------------------------------------------------------- */

const PLANET_DATA = [
  { id:'mercury', name:'Mercury', color:'#b7aa9a', order:1,
    diameter:'4,879 km', distance:'57.9M km (0.39 AU)', period:'88 days',
    moons:0, dayLength:'59 Earth days',
    tagline:'The fastest, smallest world in the Sun\u2019s orbit.',
    note:'Mercury has almost no atmosphere, so its surface swings from 430\u00b0C in daylight to \u2212180\u00b0C at night \u2014 the widest temperature range of any planet.' },
  { id:'venus', name:'Venus', color:'#e8c27a', order:2,
    diameter:'12,104 km', distance:'108.2M km (0.72 AU)', period:'225 days',
    moons:0, dayLength:'243 Earth days',
    tagline:'Earth\u2019s twin in size, and its opposite in climate.',
    note:'A runaway greenhouse effect traps heat under thick CO\u2082 clouds, making Venus the hottest planet \u2014 hotter even than Mercury.' },
  { id:'earth', name:'Earth', color:'#4f8dde', order:3,
    diameter:'12,742 km', distance:'149.6M km (1 AU)', period:'365.25 days',
    moons:1, dayLength:'24 hours',
    tagline:'The only known world with liquid water on its surface.',
    note:'Earth\u2019s magnetic field, generated by its molten iron core, deflects most solar and cosmic radiation that would otherwise strip away the atmosphere.' },
  { id:'mars', name:'Mars', color:'#c1603f', order:4,
    diameter:'6,779 km', distance:'227.9M km (1.52 AU)', period:'687 days',
    moons:2, dayLength:'24h 37m',
    tagline:'The Red Planet, and the next target for crewed landings.',
    note:'Mars hosts Olympus Mons, the largest volcano in the Solar System at roughly 22 km tall \u2014 nearly three times the height of Mount Everest.' },
  { id:'jupiter', name:'Jupiter', color:'#d9a566', order:5,
    diameter:'139,820 km', distance:'778.5M km (5.2 AU)', period:'11.86 years',
    moons:95, dayLength:'9h 56m',
    tagline:'A gas giant bigger than every other planet combined.',
    note:'The Great Red Spot is a storm wider than Earth that has raged for at least 190 years of observation, and likely far longer.' },
  { id:'saturn', name:'Saturn', color:'#e3cd9a', order:6,
    diameter:'116,460 km', distance:'1.43B km (9.58 AU)', period:'29.4 years',
    moons:146, dayLength:'10h 42m',
    tagline:'Famous for a ring system spanning over 280,000 km.',
    note:'Saturn\u2019s rings are made almost entirely of water ice, in chunks ranging from dust grains to boulders, and are only about 10 m thick on average.' },
  { id:'uranus', name:'Uranus', color:'#8fd6d6', order:7,
    diameter:'50,724 km', distance:'2.87B km (19.2 AU)', period:'84 years',
    moons:28, dayLength:'17h 14m',
    tagline:'An ice giant that spins on its side.',
    note:'Uranus is tilted roughly 98\u00b0 on its axis, likely from an ancient collision, so its poles \u2014 not its equator \u2014 face the Sun for parts of its orbit.' },
  { id:'neptune', name:'Neptune', color:'#5069c9', order:8,
    diameter:'49,244 km', distance:'4.5B km (30.1 AU)', period:'164.8 years',
    moons:16, dayLength:'16h 6m',
    tagline:'The windiest planet, with gusts over 2,000 km/h.',
    note:'Neptune radiates about 2.6 times more energy than it receives from the Sun, from heat left over from its formation.' },
];

const STAR_DATA = [
  { id:'sirius', name:'Sirius A', badge:'A1V \u2014 Main Sequence',
    meta:'8.6 light-years away \u00b7 25.4\u00d7 the Sun\u2019s luminosity',
    desc:'The brightest star in Earth\u2019s night sky, part of a binary system with a white dwarf companion, Sirius B.' },
  { id:'proxima', name:'Proxima Centauri', badge:'M5.5Ve \u2014 Red Dwarf',
    meta:'4.24 light-years away \u00b7 0.0017\u00d7 the Sun\u2019s luminosity',
    desc:'The closest known star to the Sun, orbited by at least one rocky planet, Proxima b, in its habitable zone.' },
  { id:'betelgeuse', name:'Betelgeuse', badge:'M1\u20132Ia \u2014 Red Supergiant',
    meta:'\u2248548 light-years away \u00b7 \u2248126,000\u00d7 the Sun\u2019s luminosity',
    desc:'A dying star in Orion\u2019s shoulder, expected to end in a supernova sometime in the next 100,000 years.' },
  { id:'rigel', name:'Rigel', badge:'B8Ia \u2014 Blue Supergiant',
    meta:'\u2248860 light-years away \u00b7 \u2248120,000\u00d7 the Sun\u2019s luminosity',
    desc:'Orion\u2019s brightest star, burning hot and blue-white, with a mass around 21 times that of the Sun.' },
];

const GALAXY_DATA = [
  { id:'milkyway', name:'The Milky Way', badge:'Barred Spiral',
    meta:'\u2248105,700 ly across \u00b7 100\u2013400 billion stars',
    desc:'Our home galaxy, viewed edge-on from Earth as a pale band across the night sky.' },
  { id:'andromeda', name:'Andromeda (M31)', badge:'Spiral',
    meta:'2.5 million ly away \u00b7 \u2248220,000 ly across',
    desc:'The nearest large galaxy to ours, on a slow collision course with the Milky Way roughly 4.5 billion years from now.' },
  { id:'whirlpool', name:'Whirlpool Galaxy (M51)', badge:'Spiral, interacting',
    meta:'\u224823 million ly away',
    desc:'A textbook spiral caught mid-interaction with its smaller companion galaxy, NGC 5195.' },
  { id:'sombrero', name:'Sombrero Galaxy (M104)', badge:'Spiral',
    meta:'\u224831 million ly away \u00b7 \u22481 billion M\u2609 central black hole',
    desc:'Named for its wide, bright dust lane, which resembles the brim of a hat seen edge-on.' },
];

const BLACKHOLE_DATA = [
  { id:'sagA', name:'Sagittarius A*', badge:'Supermassive',
    meta:'\u22484.3 million M\u2609 \u00b7 \u224826,000 ly away',
    desc:'The black hole at the center of the Milky Way, imaged directly by the Event Horizon Telescope in 2022.' },
  { id:'m87star', name:'M87*', badge:'Supermassive',
    meta:'\u22486.5 billion M\u2609 \u00b7 \u224853 million ly away',
    desc:'The first black hole ever directly imaged, released by the Event Horizon Telescope collaboration in 2019.' },
  { id:'cygnusx1', name:'Cygnus X-1', badge:'Stellar-mass',
    meta:'\u224821 M\u2609 \u00b7 \u22487,200 ly away',
    desc:'One of the first strong black hole candidates ever identified, discovered via X-ray emissions in 1964.' },
  { id:'ton618', name:'TON 618', badge:'Ultramassive',
    meta:'\u224866 billion M\u2609 \u00b7 \u224810.4 billion ly away',
    desc:'One of the most massive black holes known, powering a hyperluminous quasar.' },
];

const MISSION_DATA = [
  { year:'1969', name:'Apollo 11', status:'Completed',
    desc:'The first crewed Moon landing, carrying Neil Armstrong and Buzz Aldrin to the lunar surface.' },
  { year:'1977', name:'Voyager 1', status:'Active \u2014 interstellar space',
    desc:'Launched to tour the outer planets, it is now the most distant human-made object, still transmitting data.' },
  { year:'1990', name:'Hubble Space Telescope', status:'Active',
    desc:'An optical space telescope that reshaped modern astronomy with deep, sharp views of the universe.' },
  { year:'1997', name:'Cassini\u2013Huygens', status:'Completed',
    desc:'Orbited Saturn for 13 years and landed a probe on its moon Titan, before a planned atmospheric dive in 2017.' },
  { year:'2021', name:'James Webb Space Telescope', status:'Active',
    desc:'An infrared observatory built to see the earliest galaxies and probe the atmospheres of distant exoplanets.' },
  { year:'2021', name:'Perseverance Rover', status:'Active',
    desc:'Exploring Jezero Crater on Mars, collecting samples for eventual return to Earth.' },
];

const TIMELINE_DATA = [
  { epoch:'13.8 billion years ago', desc:'The Big Bang \u2014 space, time, and the earliest particles come into existence.' },
  { epoch:'13.8 billion years ago (+380,000 yrs)', desc:'The universe cools enough for light to travel freely, releasing the Cosmic Microwave Background.' },
  { epoch:'\u224813.6 billion years ago', desc:'The first stars ignite, forming from vast clouds of primordial hydrogen and helium.' },
  { epoch:'\u224813.2 billion years ago', desc:'The first galaxies begin to take shape as gravity pulls early stars together.' },
  { epoch:'4.6 billion years ago', desc:'A collapsing cloud of gas and dust forms the Sun and the rest of the Solar System.' },
  { epoch:'4.5 billion years ago', desc:'Earth forms, along with the other rocky planets, from leftover debris around the young Sun.' },
  { epoch:'\u22483.8 billion years ago', desc:'The earliest evidence of life appears in Earth\u2019s oceans.' },
  { epoch:'\u2248300,000 years ago', desc:'Homo sapiens emerges in Africa.' },
  { epoch:'1969', desc:'Humans set foot on another world for the first time, during the Apollo 11 mission.' },
  { epoch:'Today', desc:'Telescopes, rovers and probes continue to expand what we know about the cosmos \u2014 in real time.' },
];

/* -------------------------------------------------------------
   3. STARFIELD — animated canvas background
------------------------------------------------------------- */
function initStarfield(){
  const canvas = document.getElementById('starfield');
  const ctx = canvas.getContext('2d');
  let width, height, stars = [];
  let reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  function resize(){
    width = canvas.width = window.innerWidth;
    height = canvas.height = window.innerHeight * Math.max(3.2, document.body.scrollHeight / window.innerHeight);
    buildStars();
  }

  function buildStars(){
    const count = Math.min(CONFIG.starfield.maxStars, Math.floor(width * height * CONFIG.starfield.density));
    stars = new Array(count).fill(0).map(() => ({
      x: Math.random() * width,
      y: Math.random() * height,
      r: Math.random() * 1.4 + 0.3,
      baseAlpha: Math.random() * 0.6 + 0.3,
      phase: Math.random() * Math.PI * 2,
      hue: Math.random() < 0.15 ? '167,181,255' : '255,255,255',
    }));
  }

  let t = 0;
  function draw(){
    ctx.clearRect(0, 0, width, height);
    t += CONFIG.starfield.twinkleSpeed;
    for(const s of stars){
      const twinkle = reduceMotion ? 1 : (Math.sin(t + s.phase) * 0.35 + 0.65);
      ctx.beginPath();
      ctx.fillStyle = `rgba(${s.hue}, ${(s.baseAlpha * twinkle).toFixed(2)})`;
      ctx.arc(s.x, s.y, s.r, 0, Math.PI * 2);
      ctx.fill();
    }
    if(!reduceMotion){
      requestAnimationFrame(draw);
    }
  }

  window.addEventListener('resize', debounce(resize, 200));
  resize();
  draw();

  // Reposition canvas to track scrollable height (cheap, no scroll listener needed
  // since it's position:fixed covering the viewport already).
}

function debounce(fn, wait){
  let timer;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), wait);
  };
}

/* -------------------------------------------------------------
   4. RENDERERS
------------------------------------------------------------- */
function renderOrrery(){
  const orrery = document.getElementById('orrery');
  const cfg = CONFIG.orrery;

  PLANET_DATA.forEach((planet, i) => {
    const radiusPct = cfg.baseRadiusPct + i * cfg.radiusStepPct;
    const speed = 18 + i * 9; // purely visual, not to scale

    const ring = document.createElement('div');
    ring.className = 'orbit-ring';
    ring.style.width = radiusPct * 2 + '%';
    ring.style.height = radiusPct * 2 + '%';

    const spin = document.createElement('div');
    spin.className = 'orbit-spin';
    spin.style.setProperty('--orbit-speed', speed + 's');
    // stagger starting rotation so planets don't all line up
    spin.style.transform = `rotate(${(i * 47) % 360}deg)`;

    const dot = document.createElement('div');
    dot.className = 'orbit-dot';
    dot.style.setProperty('--dot-size', Math.max(6, 14 - i) + 'px');
    dot.style.setProperty('--dot-glow', planet.color + '99');
    dot.style.background = planet.color;
    dot.title = planet.name;
    dot.addEventListener('click', () => openPlanetDetail(planet));

    spin.appendChild(dot);
    ring.appendChild(spin);
    orrery.appendChild(ring);
  });
}

function renderPlanetGrid(){
  const grid = document.getElementById('planet-grid');
  grid.innerHTML = PLANET_DATA.map(p => `
    <article class="planet-card glass reveal" data-id="${p.id}" tabindex="0">
      <span class="order-tag">0${p.order} / 08</span>
      <div class="planet-swatch" style="background:${p.color}"></div>
      <h3>${p.name}</h3>
      <p class="tagline">${p.tagline}</p>
    </article>
  `).join('');

  grid.querySelectorAll('.planet-card').forEach(card => {
    const planet = PLANET_DATA.find(p => p.id === card.dataset.id);
    card.addEventListener('click', () => openPlanetDetail(planet));
    card.addEventListener('keydown', e => {
      if(e.key === 'Enter' || e.key === ' '){ e.preventDefault(); openPlanetDetail(planet); }
    });
  });
}

function renderCardRow(containerId, data, accentColor){
  const row = document.getElementById(containerId);
  row.innerHTML = data.map(item => `
    <article class="info-card glass reveal" data-id="${item.id}" tabindex="0">
      <span class="badge">${item.badge}</span>
      <h3>${item.name}</h3>
      <span class="meta">${item.meta}</span>
      <p class="desc">${item.desc}</p>
    </article>
  `).join('');

  row.querySelectorAll('.info-card').forEach(card => {
    const item = data.find(d => d.id === card.dataset.id);
    card.addEventListener('click', () => openGenericDetail(item, accentColor));
    card.addEventListener('keydown', e => {
      if(e.key === 'Enter' || e.key === ' '){ e.preventDefault(); openGenericDetail(item, accentColor); }
    });
  });
}

function renderMissions(){
  const grid = document.getElementById('mission-grid');
  grid.innerHTML = MISSION_DATA.map(m => `
    <article class="mission-card glass reveal">
      <span class="year">${m.year}</span>
      <h3>${m.name}</h3>
      <p>${m.desc}</p>
      <span class="status">${m.status}</span>
    </article>
  `).join('');
}

function renderTimeline(){
  const track = document.getElementById('timeline-track');
  track.innerHTML = TIMELINE_DATA.map(t => `
    <div class="timeline-entry reveal">
      <div class="t-epoch">${t.epoch}</div>
      <div class="t-desc">${t.desc}</div>
    </div>
  `).join('');
}

/* -------------------------------------------------------------
   5. DETAIL OVERLAY
------------------------------------------------------------- */
const overlay = () => document.getElementById('detail-overlay');
const detailBody = () => document.getElementById('detail-body');

function openPlanetDetail(p){
  detailBody().innerHTML = `
    <div class="d-swatch" style="background:${p.color}"></div>
    <h3 id="detail-title">${p.name}</h3>
    <div class="d-meta">Planet 0${p.order} from the Sun</div>
    <dl>
      <dt>Diameter</dt><dd>${p.diameter}</dd>
      <dt>Distance from Sun</dt><dd>${p.distance}</dd>
      <dt>Orbital period</dt><dd>${p.period}</dd>
      <dt>Day length</dt><dd>${p.dayLength}</dd>
      <dt>Moons</dt><dd>${p.moons}</dd>
    </dl>
    <p class="d-note">${p.note}</p>
  `;
  openOverlay();
}

function openGenericDetail(item, accentColor){
  detailBody().innerHTML = `
    <div class="d-swatch" style="background:${accentColor}"></div>
    <h3 id="detail-title">${item.name}</h3>
    <div class="d-meta">${item.badge}</div>
    <p class="d-note">${item.meta}</p>
    <p class="d-note">${item.desc}</p>
  `;
  openOverlay();
}

function openOverlay(){
  overlay().classList.add('is-open');
  document.body.style.overflow = 'hidden';
}
function closeOverlay(){
  overlay().classList.remove('is-open');
  document.body.style.overflow = '';
}

/* -------------------------------------------------------------
   6. NAV / SCROLL BEHAVIOUR
------------------------------------------------------------- */
function initNav(){
  const toggle = document.getElementById('nav-toggle');
  const nav = document.getElementById('primary-nav');

  toggle.addEventListener('click', () => {
    const isOpen = nav.classList.toggle('is-open');
    toggle.setAttribute('aria-expanded', String(isOpen));
  });

  nav.querySelectorAll('a').forEach(link => {
    link.addEventListener('click', () => {
      nav.classList.remove('is-open');
      toggle.setAttribute('aria-expanded', 'false');
    });
  });
}

function initRevealOnScroll(){
  const io = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if(entry.isIntersecting){
        entry.target.classList.add('is-visible');
        io.unobserve(entry.target);
      }
    });
  }, { threshold: 0.15, rootMargin: '0px 0px -40px 0px' });

  document.querySelectorAll('.reveal').forEach(el => io.observe(el));
}

function initDetailOverlay(){
  document.getElementById('detail-close').addEventListener('click', closeOverlay);
  overlay().addEventListener('click', (e) => {
    if(e.target === overlay()) closeOverlay();
  });
  document.addEventListener('keydown', (e) => {
    if(e.key === 'Escape') closeOverlay();
  });
}

/* -------------------------------------------------------------
   Future hook — live data
   Replace the static DATA arrays above with results from a real
   astronomy API (e.g. NASA Open APIs, JPL Horizons, Le Système
   Solaire API). Keep each record's shape identical to what the
   renderers already expect, then re-run the render* functions.
------------------------------------------------------------- */
async function fetchLiveData(){
  // Example shape for later:
  // const res = await fetch('https://api.example.com/planets');
  // const live = await res.json();
  // PLANET_DATA.length = 0; PLANET_DATA.push(...live);
  // renderOrrery(); renderPlanetGrid();
  return null;
}

/* -------------------------------------------------------------
   Future hook — 3D bodies
   This container is where a WebGL/Three.js render of the hero
   planet (or a full 3D orrery) can be mounted later without
   restructuring the surrounding layout.
------------------------------------------------------------- */
function mount3DHero(){
  // const container = document.querySelector('.hero-planet');
  // Initialize a Three.js scene/camera/renderer into `container`
  // in place of the current CSS-rendered planet.
}

/* -------------------------------------------------------------
   7. INIT
------------------------------------------------------------- */
document.addEventListener('DOMContentLoaded', () => {
  initStarfield();
  renderOrrery();
  renderPlanetGrid();
  renderCardRow('star-row', STAR_DATA, '#e8b96a');
  renderCardRow('galaxy-row', GALAXY_DATA, '#7a5cf0');
  renderCardRow('blackhole-row', BLACKHOLE_DATA, '#3f6fd1');
  renderMissions();
  renderTimeline();
  initNav();
  initDetailOverlay();
  initRevealOnScroll();
});
